## Nombre: Adalía Fernanda Aneiros Gutiérrez                               Matricula: A00832680

## Nombre: Valeria Edith Lugo Gutiérrez                                       Matricula: A00830523

## Nombre: Yuu Ricardo Akachi Tanaka 		Matrícula:A01351969

## Nombre: Pablo Monzon Terrazas 		Matrícula:A01562619

## Nombre: Donnet Hernández Franco 	  Matricula: A01352049

## Nombre: Luis Alejo Muñoz Ledo 	  Matricula: A01704173

## Lectura de la base de datos con 40 nodos aleatorios  

In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta1_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        ,  3.73541499,  3.83223901, ...,  7.95447155,
        10.0574647 ,  2.17989099],
       [ 3.73541499,  0.        ,  4.69974601, ..., 11.62821644,
        13.14553513,  2.8241823 ],
       [ 3.83223901,  4.69974601,  0.        , ...,  8.86547999,
         9.01765022,  2.16409622],
       ...,
       [ 7.95447155, 11.62821644,  8.86547999, ...,  0.        ,
         4.7031951 ,  9.19867387],
       [10.0574647 , 13.14553513,  9.01765022, ...,  4.7031951 ,
         0.        , 10.34204925],
       [ 2.17989099,  2.8241823 ,  2.16409622, ...,  9.19867387,
        10.34204925,  0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 28, 23, 4, 8, 27, 9, 15, 10, 24, 35, 17, 25, 11, 20, 7, 14, 1, 21, 29, 36, 31, 26, 32, 19, 2, 22, 18, 3, 16, 38, 33, 37, 6, 5, 34, 30, 39, 13, 12]
Costo de la mejor ruta: 70.320589903


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta2_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        ,  3.47266085,  9.86257153, ...,  1.73992026,
        11.67993893, 11.12214829],
       [ 3.47266085,  0.        ,  8.82528668, ...,  1.76337143,
        10.37910417, 11.32901438],
       [ 9.86257153,  8.82528668,  0.        , ...,  8.97956279,
         1.89324513,  4.15934317],
       ...,
       [ 1.73992026,  1.76337143,  8.97956279, ...,  0.        ,
        10.70241445, 10.85955179],
       [11.67993893, 10.37910417,  1.89324513, ..., 10.70241445,
         0.        ,  4.89767779],
       [11.12214829, 11.32901438,  4.15934317, ..., 10.85955179,
         4.89767779,  0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 31, 37, 30, 7, 1, 12, 29, 16, 5, 28, 2, 20, 10, 15, 38, 27, 9, 8, 13, 33, 6, 11, 22, 18, 39, 25, 34, 4, 26, 36, 24, 35, 14, 17, 19, 23, 3, 21, 32]
Costo de la mejor ruta: 71.17437900700001


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta3_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        ,  0.68657521, 14.89500677, ...,  0.42636844,
         9.26329579,  7.49230024],
       [ 0.68657521,  0.        , 14.9065163 , ...,  0.94745887,
         9.68799626,  7.24959976],
       [14.89500677, 14.9065163 ,  0.        , ..., 14.50984688,
         9.33048633,  8.50102668],
       ...,
       [ 0.42636844,  0.94745887, 14.50984688, ...,  0.        ,
         8.84649223,  7.21317578],
       [ 9.26329579,  9.68799626,  9.33048633, ...,  8.84649223,
         0.        ,  8.48504082],
       [ 7.49230024,  7.24959976,  8.50102668, ...,  7.21317578,
         8.48504082,  0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 37, 1, 7, 5, 19, 10, 32, 12, 39, 36, 14, 35, 28, 31, 33, 30, 11, 2, 15, 20, 16, 24, 34, 8, 23, 29, 18, 3, 38, 9, 17, 6, 13, 22, 4, 27, 25, 26, 21]
Costo de la mejor ruta: 62.429757149


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta4_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        ,  7.25184083, 11.61305167, ..., 13.59543491,
        12.35502609,  8.40538964],
       [ 7.25184083,  0.        ,  9.25121888, ...,  7.03826533,
        10.42286031,  8.32491559],
       [11.61305167,  9.25121888,  0.        , ...,  7.83733884,
         1.21329062,  3.72116508],
       ...,
       [13.59543491,  7.03826533,  7.83733884, ...,  0.        ,
         8.89189441,  9.84614021],
       [12.35502609, 10.42286031,  1.21329062, ...,  8.89189441,
         0.        ,  4.10839324],
       [ 8.40538964,  8.32491559,  3.72116508, ...,  9.84614021,
         4.10839324,  0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 8, 13, 9, 19, 22, 35, 25, 30, 17, 21, 39, 33, 27, 14, 6, 4, 3, 23, 12, 7, 28, 29, 15, 5, 36, 38, 20, 18, 26, 16, 2, 24, 11, 37, 34, 31, 10, 1, 32]
Costo de la mejor ruta: 69.206560964


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta5_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[0.        , 5.58677317, 7.08744613, ..., 5.81616744, 6.94172063,
        5.46070555],
       [5.58677317, 0.        , 1.50140581, ..., 2.32615091, 5.11232006,
        4.97714129],
       [7.08744613, 1.50140581, 0.        , ..., 2.94283532, 5.50609812,
        5.8751521 ],
       ...,
       [5.81616744, 2.32615091, 2.94283532, ..., 0.        , 7.38083375,
        2.94915171],
       [6.94172063, 5.11232006, 5.50609812, ..., 7.38083375, 0.        ,
        9.55993812],
       [5.46070555, 4.97714129, 5.8751521 , ..., 2.94915171, 9.55993812,
        0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 36, 7, 9, 27, 26, 39, 23, 25, 14, 37, 1, 34, 2, 8, 16, 13, 4, 19, 28, 31, 11, 5, 3, 33, 35, 29, 10, 18, 38, 12, 24, 22, 30, 17, 20, 15, 6, 32, 21]
Costo de la mejor ruta: 74.82260797400001


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta6_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[0.        , 5.45918668, 5.4394009 , ..., 2.26435208, 3.83442507,
        1.39949585],
       [5.45918668, 0.        , 2.19592703, ..., 3.85228251, 1.78202619,
        5.86976637],
       [5.4394009 , 2.19592703, 0.        , ..., 3.26432122, 3.01308328,
        6.31870624],
       ...,
       [2.26435208, 3.85228251, 3.26432122, ..., 0.        , 2.74114349,
        3.41021404],
       [3.83442507, 1.78202619, 3.01308328, ..., 2.74114349, 0.        ,
        4.10412859],
       [1.39949585, 5.86976637, 6.31870624, ..., 3.41021404, 4.10412859,
        0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 39, 32, 4, 28, 38, 27, 1, 19, 30, 13, 2, 36, 5, 11, 15, 21, 7, 9, 31, 35, 33, 25, 22, 16, 18, 17, 12, 23, 24, 14, 8, 10, 37, 6, 3, 29, 26, 34, 20]
Costo de la mejor ruta: 74.48643990099998


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta7_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        , 10.49822055, 14.04959612, ..., 12.2889432 ,
        11.69626461, 14.14993175],
       [10.49822055,  0.        ,  4.74142855, ...,  2.30822351,
         2.05097857,  4.75884345],
       [14.04959612,  4.74142855,  0.        , ...,  5.3600042 ,
         2.73669792,  7.11960599],
       ...,
       [12.2889432 ,  2.30822351,  5.3600042 , ...,  0.        ,
         3.38265621,  2.46544336],
       [11.69626461,  2.05097857,  2.73669792, ...,  3.38265621,
         0.        ,  5.68592281],
       [14.14993175,  4.75884345,  7.11960599, ...,  2.46544336,
         5.68592281,  0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 28, 5, 17, 12, 27, 7, 24, 3, 18, 34, 14, 33, 23, 32, 13, 15, 36, 39, 4, 37, 21, 1, 16, 35, 26, 38, 10, 20, 9, 11, 29, 2, 25, 6, 19, 22, 8, 31, 30]
Costo de la mejor ruta: 60.534666727


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta8_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        ,  6.11506299,  7.01920186, ...,  2.67425896,
         9.53244972,  2.26351575],
       [ 6.11506299,  0.        ,  8.32796317, ...,  4.42027007,
         9.44395414,  5.64328389],
       [ 7.01920186,  8.32796317,  0.        , ...,  5.189746  ,
         2.75728324,  8.9800658 ],
       ...,
       [ 2.67425896,  4.42027007,  5.189746  , ...,  0.        ,
         7.34806888,  3.98836735],
       [ 9.53244972,  9.44395414,  2.75728324, ...,  7.34806888,
         0.        , 11.31070186],
       [ 2.26351575,  5.64328389,  8.9800658 , ...,  3.98836735,
        11.31070186,  0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 39, 5, 3, 32, 19, 16, 10, 37, 8, 11, 24, 30, 33, 17, 2, 25, 6, 29, 15, 21, 9, 38, 28, 36, 18, 7, 4, 12, 34, 26, 22, 23, 20, 35, 31, 27, 14, 1, 13]
Costo de la mejor ruta: 59.776342827


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta9_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        ,  9.24490705,  2.02900342, ...,  8.89390056,
         5.16569252,  4.63410287],
       [ 9.24490705,  0.        , 11.21531823, ...,  1.44830518,
         9.18592922,  8.12600341],
       [ 2.02900342, 11.21531823,  0.        , ..., 10.91278517,
         6.47697477,  6.21256844],
       ...,
       [ 8.89390056,  1.44830518, 10.91278517, ...,  0.        ,
         8.11215775,  7.10643001],
       [ 5.16569252,  9.18592922,  6.47697477, ...,  8.11215775,
         0.        ,  1.12394867],
       [ 4.63410287,  8.12600341,  6.21256844, ...,  7.10643001,
         1.12394867,  0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 21, 24, 2, 30, 14, 10, 15, 5, 26, 32, 4, 3, 19, 27, 38, 39, 13, 36, 28, 7, 6, 33, 35, 1, 16, 18, 37, 12, 31, 9, 23, 11, 25, 34, 29, 8, 20, 22, 17]
Costo de la mejor ruta: 65.558156814


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/Ruta10_40nodos.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((40, 40))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        ,  9.74397736,  7.25704647, ...,  7.52715541,
         9.26166675,  8.61174111],
       [ 9.74397736,  0.        , 11.66913068, ...,  2.81696769,
        12.5538982 ,  4.17455467],
       [ 7.25704647, 11.66913068,  0.        , ...,  8.87022514,
         2.04205296,  8.02322155],
       ...,
       [ 7.52715541,  2.81696769,  8.87022514, ...,  0.        ,
         9.85001613,  2.20437591],
       [ 9.26166675, 12.5538982 ,  2.04205296, ...,  9.85001613,
         0.        ,  8.58870404],
       [ 8.61174111,  4.17455467,  8.02322155, ...,  2.20437591,
         8.58870404,  0.        ]])

In [ ]:
import numpy as np
import random

n = 40
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 40:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]

            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 16, 29, 36, 5, 19, 11, 12, 20, 30, 31, 37, 27, 1, 26, 18, 23, 13, 39, 28, 7, 21, 10, 24, 3, 9, 17, 2, 38, 33, 4, 34, 25, 15, 22, 32, 6, 35, 8, 14]
Costo de la mejor ruta: 81.85709246800002


In [ ]:
import pandas as pd
import numpy as np
df=pd.read_csv("/content/distancias_100.csv")
matriz_costo=df.to_numpy()
np.fill_diagonal(matriz_costo, 0)
tau_i_j = 0.1 * np.ones((100, 100))
np.fill_diagonal(tau_i_j, 0)
matriz_costo

array([[ 0.        ,  4.67656552,  7.7619877 , ...,  5.70391201,
         5.90147156,  8.72937411],
       [ 4.67656552,  0.        , 11.86061776, ..., 10.3737404 ,
        10.48125118, 13.14900931],
       [ 7.7619877 , 11.86061776,  0.        , ...,  4.21473016,
         3.05457282,  2.05543399],
       ...,
       [ 5.70391201, 10.3737404 ,  4.21473016, ...,  0.        ,
         1.17622205,  3.85108256],
       [ 5.90147156, 10.48125118,  3.05457282, ...,  1.17622205,
         0.        ,  2.99873078],
       [ 8.72937411, 13.14900931,  2.05543399, ...,  3.85108256,
         2.99873078,  0.        ]])

In [ ]:
import numpy as np
import random

n = 100
m = 40
alpha = 1.0
beta = 2.0
ro = 0.1
Q = 1.0
n_iteraciones = 1000


for iteracion in range(n_iteraciones):
    ruta_hormigas = []
    costo_hormigas = []

    for hormiga in range(m):
        nodo_actual = 0
        ruta = [nodo_actual]
        costo = 0

        while len(ruta) < 100:

            no_visitados = [i for i in range(n) if i not in ruta]
            probabilidad = np.zeros(n)
            visitado = [i for i in range (n) if i in ruta]


            for i in no_visitados:
                probabilidad[i] = (tau_i_j[nodo_actual][i] ** alpha) * (1.0 / matriz_costo[nodo_actual][i] ** beta)

            probabilidad /= probabilidad.sum()
            probabilidad = np.delete(probabilidad, visitado)
            nodo_siguiente = np.random.choice(no_visitados, p=probabilidad)
            costo += matriz_costo[nodo_actual][nodo_siguiente]
            ruta.append(nodo_siguiente)
            nodo_actual = nodo_siguiente

        costo += matriz_costo[ruta[-1]][ruta[0]]
        ruta_hormigas.append(ruta)
        costo_hormigas.append(costo)


    for i in range(n):
        for j in range(n):
            tau_i_j[i][j] = (1 - ro) * tau_i_j[i][j]

    for hormiga in range(m):
        for i in range(1,len(ruta_hormigas[hormiga])):
            tau_i_j[ruta_hormigas[hormiga][i-1]][ruta_hormigas[hormiga][i]] += (Q / costo_hormigas[hormiga])

print(ruta_hormigas[np.argmin(costo_hormigas)])
print("Costo de la mejor ruta:", min(costo_hormigas))

[0, 36, 20, 11, 48, 96, 23, 32, 15, 31, 13, 28, 46, 54, 87, 39, 92, 63, 27, 16, 78, 62, 64, 25, 52, 82, 51, 99, 17, 49, 89, 81, 91, 42, 18, 60, 30, 2, 68, 95, 26, 69, 76, 21, 38, 4, 88, 65, 84, 72, 67, 5, 80, 14, 59, 35, 47, 41, 85, 56, 37, 45, 73, 57, 24, 6, 93, 12, 55, 94, 53, 33, 61, 34, 3, 10, 74, 1, 40, 83, 8, 44, 7, 43, 58, 71, 66, 9, 77, 70, 86, 29, 98, 97, 75, 22, 90, 19, 50, 79]
Costo de la mejor ruta: 104.08733350800001
